### ISSUE TITLE
Parse Error when calling enrollment endpoint

### ISSUE THREAD

**Issue by ravengit** [IBM-Blockchain-Archive/marbles#102]
Running Fabric v1.0.0-alpha1 locally. "fabric-ca" container looks to be running and it says everything is successful when doing "network_setup.sh up"

Please advise. Thanks.

```
info: [FabricCAClientImpl.js]: Successfully constructed Fabric CA service client: endpoint - %j protocol=http, hostname=localhost, port=7054
debug: id admin secret adminpw
debug: msp_id Org1MSP
info: [crypto_ecdsa_aes]: This class requires a CryptoKeyStore to save keys, using the store: {"opts":{"path":"/Users/cso/.hfc-key-store"}}
error: Error: Calling enrollment endpoint failed with error [Error: Parse Error]
    at ClientRequest.<anonymous> (/Users/cso/projects/marbles.v3/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:568:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnData (_http_client.js:368:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
error: [fcw] Failed to get enrollment marbles-e2ecli_default-mychannel-fabric-peer-1a Error: Failed to obtain an enrolled user
    at ca_client.enroll.then.then.then.catch (/Users/cso/projects/marbles.v3/utils/fc_wrangler/enrollment.js:167:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
error: [fcw] could not format error
error: could not enroll...
```

**Comment by dshuffma-ibm** [comment]
get into the container logs for the CA on port `7054` to get more information. 

also triple check that the ip/ports you fed marbles are correct and you didn't accidentally mix up a peer with a CA or something.

**Comment by ravengit** [comment]
Can someone advise where I can find the log for fabric-ca-server? I ssh into the docker container and can't find any log for fabric-ca-server.

**Comment by vmorris** [comment]
Try `docker logs <CONTAINER>`

**Comment by ravengit** [comment]
Okay. I see these error messages in fabric-ca-server "docker logs" when the Parse Error happens.

Any idea why?

```
2017/05/25 18:01:12 [INFO] Listening on https://0.0.0.0:7054
2017/05/25 18:02:53 http: TLS handshake error from 10.0.2.2:55696: tls: oversized record received with length 21536
2017/05/25 18:02:53 http: TLS handshake error from 10.0.2.2:55697: tls: oversized record received with length 21536
2017/05/25 18:02:56 http: TLS handshake error from 10.0.2.2:55699: tls: oversized record received with length 21536
2017/05/25 18:02:56 http: TLS handshake error from 10.0.2.2:55700: tls: oversized record received with length 21536
2017/05/25 18:04:31 http: TLS handshake error from 10.0.2.2:55702: tls: oversized record received with length 21536
2017/05/25 18:04:31 http: TLS handshake error from 10.0.2.2:55709: tls: oversized record received with length 21536
2017/05/25 18:04:36 http: TLS handshake error from 10.0.2.2:55711: tls: oversized record received with length 21536
2017/05/25 18:04:36 http: TLS handshake error from 10.0.2.2:55712: tls: oversized record received with length 21536
```

**Comment by vmorris** [comment]
It looks like you are trying to use TLS on http, not https....

**Comment by ravengit** [comment]
Yes I also just found that out. But using https gives me another error:

```
info: [FabricCAClientImpl.js]: Successfully constructed Fabric CA service client: endpoint - %j protocol=https, hostname=127.0.0.1, port=7054
debug: id admin secret adminpw
debug: msp_id Org1MSP
info: [crypto_ecdsa_aes]: This class requires a CryptoKeyStore to save keys, using the store: {"opts":{"path":"/Users/cso/.hfc-key-store"}}
error: Error: Could not parse enrollment response [404 page not found
] as JSON due to error [SyntaxError: Unexpected token p in JSON at position 4]
    at IncomingMessage.<anonymous> (/Users/cso/projects/marbles.v3/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:560:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error: [fcw] Failed to get enrollment marbles-e2ecli_default-mychannel-fabric-peer-1a Error: Failed to obtain an enrolled user
    at ca_client.enroll.then.then.then.catch (/Users/cso/projects/marbles.v3/utils/fc_wrangler/enrollment.js:167:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
error: [fcw] could not format error
error: could not enroll...
```

**Comment by ravengit** [comment]
I'm not sure if my set up causes this issue:

1. Guest OS (Vagrant + VirtualBox) running the ubuntu which dos the ./network_setup.sh
2. Host OS runs marbles v3

Not sure why there is 404 error. I'm able to do "telnet localhost 7054"

**Comment by ravengit** [comment]
I think this issue is related to using http instead of https. So I'm closing this ticket.

**Comment by saan099** [comment]
hey @ravengit  were you able to solve the 404 error?? Im stuck at the same exact spot.
