### ISSUE TITLE
running gulp

### ISSUE THREAD

**Issue by knasim** [IBM-Blockchain-Archive/marbles#120]
Error: Cannot find module 'fabric-client/lib/Peer.js

 `  at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/nasimk/git/marbles/utils/fc_wrangler/deploy_cc.js:8:13)
    at module.exports (/Users/nasimk/git/marbles/utils/fc_wrangler/index.js:6:43)
    at Object.<anonymous> (/Users/nasimk/git/marbles/app.js:34:50)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)`

**Comment by dshuffma-ibm** [comment]
your SDK install was not successful or something like that.  did you run both [npm install steps](https://github.com/IBM-Blockchain/marbles/blob/v3.0/docs/host_marbles_locally.md#host-marbles-locally)?

**Comment by knasim** [comment]
i'll give it another shot - i'm on a mac.

**Comment by nokanoka** [comment]
In my mac environment I need to use node v6.9.1 . I fail "npm install" with node v7.
I used [nvm](https://github.com/creationix/nvm/blob/master/README.md) to use lower node version.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
