### ISSUE TITLE
Cannot build fabric-sdk-node, setup-sdk script seems outdated

### ISSUE THREAD

**Issue by jwgmeligmeyling** [IBM-Blockchain-Archive/marbles#137]
1) Had to run ./setup-sdk without `sudo` (despite what the README says).
2) Had to exclude `npm install -g gulp` due to the above, but that could easily be done manually
3) The script still fails with the following error: (not nodegyp again... that thing is pure evil)

```
Jan-Willems-MBP:fabric-sdk-node jgmeligmeyling$ npm install

> hashtable@2.0.2 install /Users/jgmeligmeyling/git/marbles/scripts/fabric-sdk-node/node_modules/hashtable
> node-gyp configure build

  CXX(target) Release/obj.target/native/src/hashtable.o
In file included from ../src/hashtable.cpp:1:
../src/hashtable.h:7:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
         ^
1 error generated.
make: *** [Release/obj.target/native/src/hashtable.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/jgmeligmeyling/git/marbles/scripts/fabric-sdk-node/node_modules/hashtable
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jgmeligmeyling/.npm/_logs/2017-08-18T15_23_01_720Z-debug.log
```

**Comment by dshuffma-ibm** [comment]
1. try the latest instructions on [marbles v4.0](https://github.com/IBM-Blockchain/marbles/blob/v4.0/docs/use_local_hyperledger.md) (was updated today) (there is no more sdk setup script)

**Comment by jwgmeligmeyling** [comment]
Thanks for the quick response, I'll try tomorrow!

**Comment by dshuffma-ibm** [comment]
closing, inactivity
