### ISSUE TITLE
Help!! Failed to execute query cars. Connect Failed!!

### ISSUE THREAD

**Issue by fifahuihua** [IBM-Blockchain-Archive/marbles#190]
hi, All

Please help me on this problem, thanks much in advance!! This problem blocked and depressed me long time~~~ :(
In my local, I can setup the fabric network correctly. And there is no any problem to execute 
1. node enrollAdmin.js
2. node node registerUsers.js

But when I execute the command of querying cars, it always failed!! 
```
$ node query.js
Store path:/home/antony/fabric-samples/fabcar/hfc-key-store
Successfully loaded user1 from persistence
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /home/antony/fabric-samples/fabcar/node_modules/grpc/src/client.js:554:15
Query has completed, checking results
error from query =  { Error: Connect Failed
    at /home/antony/fabric-samples/fabcar/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
```

**My local docker containers:** 
```
antony@antony-vm:~/fabric-samples/fabcar$ docker container ps
CONTAINER ID        IMAGE                                                                                                    COMMAND                  CREATED             STATUS              PORTS                                            NAMES
06cd56e4fbbf        dev-peer0.org1.example.com-fabcar-1.0-5c906e402ed29f20260ae42283216aa75549c571e2e380f3615826365d8269ba   "chaincode -peer.add…"   9 minutes ago       Up 9 minutes                                                         dev-peer0.org1.example.com-fabcar-1.0
1acd8ffaf78b        hyperledger/fabric-tools                                                                                 "/bin/bash"              10 minutes ago      Up 10 minutes                                                        cli
fbbe0584ff86        hyperledger/fabric-peer                                                                                  "peer node start"        10 minutes ago      Up 10 minutes       0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
fd421e4f397d        hyperledger/fabric-orderer                                                                               "orderer"                10 minutes ago      Up 10 minutes       0.0.0.0:7050->7050/tcp                           orderer.example.com
7bdab6844cb3        hyperledger/fabric-ca                                                                                    "sh -c 'fabric-ca-se…"   10 minutes ago      Up 10 minutes       0.0.0.0:7054->7054/tcp                           ca.example.com
e2f20e0bb4fc        hyperledger/fabric-couchdb                                                                               "tini -- /docker-ent…"   10 minutes ago      Up 10 minutes       4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb

```

**My local environments:**
```
Docker:  Docker version 17.12.0-ce, build c97c6d6
Docker-composer:  docker-compose version 1.16.1, build 6d1ac21
Go: go version go1.9.2 linux/amd64
Linux: Ubuntu 16.04 (Virtual Machine in Win7)
Node.js: v6.12.3
```

**My local docker images:**
```
antony@antony-vm:~/fabric-samples/fabcar$ docker images
REPOSITORY                                                                                               TAG                  IMAGE ID            CREATED             SIZE
dev-peer0.org1.example.com-fabcar-1.0-5c906e402ed29f20260ae42283216aa75549c571e2e380f3615826365d8269ba   latest               76e37dfaf63a        12 minutes ago      145MB
altoros/fabric-rest                                                                                      latest               f3efb76abadb        26 hours ago        400MB
hyperledger/fabric-ca                                                                                    x86_64-1.1.0-alpha   d227fe58e6e8        4 weeks ago         265MB
hyperledger/fabric-tools                                                                                 x86_64-1.1.0-alpha   b7b3d30505d4        4 weeks ago         1.44GB
hyperledger/fabric-orderer                                                                               x86_64-1.1.0-alpha   1750a681d781        4 weeks ago         163MB
hyperledger/fabric-peer                                                                                  x86_64-1.1.0-alpha   f00c5d490d19        4 weeks ago         170MB
hyperledger/fabric-javaenv                                                                               x86_64-1.1.0-alpha   a96365529cdd        4 weeks ago         1.51GB
hyperledger/fabric-ccenv                                                                                 x86_64-1.1.0-alpha   ae98dd3e9586        4 weeks ago         1.37GB
hyperledger/fabric-baseimage                                                                             x86_64-0.4.5         68e52098f6df        5 weeks ago         1.35GB
hyperledger/fabric-zookeeper                                                                             x86_64-0.4.5         70f6582e5e46        5 weeks ago         1.3GB
hyperledger/fabric-kafka                                                                                 x86_64-0.4.5         87435f68ce56        5 weeks ago         1.3GB
hyperledger/fabric-couchdb                                                                               x86_64-0.4.5         2a889ae9e597        5 weeks ago         1.5GB
hyperledger/fabric-baseos                                                                                x86_64-0.4.5         42a4582d110d        5 weeks ago         134MB
hyperledger/fabric-ca                                                                                    latest               8e691b3509bf        4 months ago        238MB
hyperledger/fabric-ca                                                                                    x86_64-1.0.4         8e691b3509bf        4 months ago        238MB
hyperledger/fabric-tools                                                                                 latest               6051774928a6        4 months ago        1.33GB
hyperledger/fabric-tools                                                                                 x86_64-1.0.4         6051774928a6        4 months ago        1.33GB
hyperledger/fabric-couchdb                                                                               latest               cf24b91dfeb1        4 months ago        1.5GB
hyperledger/fabric-couchdb                                                                               x86_64-1.0.4         cf24b91dfeb1        4 months ago        1.5GB
hyperledger/fabric-kafka                                                                                 latest               7a9d6f3c4a7c        4 months ago        1.29GB
hyperledger/fabric-kafka                                                                                 x86_64-1.0.4         7a9d6f3c4a7c        4 months ago        1.29GB
hyperledger/fabric-zookeeper                                                                             latest               53c4a0d95fd4        4 months ago        1.3GB
hyperledger/fabric-zookeeper                                                                             x86_64-1.0.4         53c4a0d95fd4        4 months ago        1.3GB
hyperledger/fabric-orderer                                                                               latest               b17741e7b036        4 months ago        151MB
hyperledger/fabric-orderer                                                                               x86_64-1.0.4         b17741e7b036        4 months ago        151MB
hyperledger/fabric-peer                                                                                  latest               1ce935adc397        4 months ago        154MB
hyperledger/fabric-peer                                                                                  x86_64-1.0.4         1ce935adc397        4 months ago        154MB
hyperledger/fabric-javaenv                                                                               latest               a517b70135c7        4 months ago        1.41GB
hyperledger/fabric-javaenv                                                                               x86_64-1.0.4         a517b70135c7        4 months ago        1.41GB
hyperledger/fabric-ccenv                                                                                 latest               856061b1fed7        4 months ago        1.28GB
hyperledger/fabric-ccenv                                                                                 x86_64-1.0.4         856061b1fed7        4 months ago        1.28GB
maxxx1313/fabric-rest                                                                                    latest               84e9271c5a05        5 months ago        400MB
hyperledger/fabric-baseos                                                                                x86_64-0.3.2         bbcbb9da2d83        6 months ago        129MB
maxxx1313/fabric-rest                                                                                    core                 412dc399d89c        6 months ago        389MB

```

If I execute the chaincode query in CLI container, it works well!! It seems that there is problem with my local fabric netork, I can't connect to peer with gPRC. 
```
$ docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" cli peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n fabcar -c '{"function":"queryAllCars","Args":[""]}'
``` 
**it returns:** 
```
2018-03-02 08:46:06.725 UTC [msp] GetLocalMSP -> DEBU 001 Returning existing local MSP
2018-03-02 08:46:06.725 UTC [msp] GetDefaultSigningIdentity -> DEBU 002 Obtaining default signing identity
2018-03-02 08:46:06.727 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 003 Using default escc
2018-03-02 08:46:06.727 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 004 Using default vscc
2018-03-02 08:46:06.728 UTC [msp/identity] Sign -> DEBU 005 Sign: plaintext: 0A93070A6908031A0C08CE9EE4D40510...0A0C7175657279416C6C436172730A00
2018-03-02 08:46:06.728 UTC [msp/identity] Sign -> DEBU 006 Sign: digest: 4B81815D0B14801202EE696A63B495555CB592833F705779B7238B9635E6D84C
2018-03-02 08:46:06.841 UTC [msp/identity] Sign -> DEBU 007 Sign: plaintext: 0A93070A6908031A0C08CE9EE4D40510...17B5B1BE18F95441A63A5B5F1110255E
2018-03-02 08:46:06.841 UTC [msp/identity] Sign -> DEBU 008 Sign: digest: AA32C758027DEAF48972727B32A75C511E1DECA3E418E65805EFA5459E08D0D9
2018-03-02 08:46:06.852 UTC [chaincodeCmd] chaincodeInvokeOrQuery -> DEBU 009 ESCC invoke result: version:1 response:<status:200 message:"OK" payload:"[{\"Key\":\"CAR0\", \"Record\":{\"colour\":\"blue\",\"make\":\"Toyota\",\"model\":\"Prius\",\"owner\":\"Tomoko\"}},{\"Key\":\"CAR1\", \"Record\":{\"colour\":\"red\",\"make\":\"Ford\",\"model\":\"Mustang\",\"owner\":\"Brad\"}},{\"Key\":\"CAR2\", \"Record\":{\"colour\":\"green\",\"make\":\"Hyundai\",\"model\":\"Tucson\",\"owner\":\"Jin Soo\"}},{\"Key\":\"CAR3\", \"Record\":{\"colour\":\"yellow\",\"make\":\"Volkswagen\",\"model\":\"Passat\",\"owner\":\"Max\"}},{\"Key\":\"CAR4\", \"Record\":{\"colour\":\"black\",\"make\":\"Tesla\",\"model\":\"S\",\"owner\":\"Adriana\"}},{\"Key\":\"CAR5\", \"Record\":{\"colour\":\"purple\",\"make\":\"Peugeot\",\"model\":\"205\",\"owner\":\"Michel\"}},{\"Key\":\"CAR6\", \"Record\":{\"colour\":\"white\",\"make\":\"Chery\",\"model\":\"S22L\",\"owner\":\"Aarav\"}},{\"Key\":\"CAR7\", \"Record\":{\"colour\":\"violet\",\"make\":\"Fiat\",\"model\":\"Punto\",\"owner\":\"Pari\"}},{\"Key\":\"CAR8\", \"Record\":{\"colour\":\"indigo\",\"make\":\"Tata\",\"model\":\"Nano\",\"owner\":\"Valeria\"}},{\"Key\":\"CAR9\", \"Record\":{\"colour\":\"brown\",\"make\":\"Holden\",\"model\":\"Barina\",\"owner\":\"Shotaro\"}}]" > payload:"\n {#\346_\250{\000F\326\033\254\250\221\345~\357\375\232vs\2736\274\201$\354W\251+\237\214s\022\351\010\n\263\001\022\230\001\n\006fabcar\022\215\001\022\212\001\n\004CAR0\022\006CAR999\030\001\"x\n\n\n\004CAR0\022\002\010\002\n\n\n\004CAR1\022\002\010\002\n\n\n\004CAR2\022\002\010\002\n\n\n\004CAR3\022\002\010\002\n\n\n\004CAR4\022\002\010\002\n\n\n\004CAR5\022\002\010\002\n\n\n\004CAR6\022\002\010\002\n\n\n\004CAR7\022\002\010\002\n\n\n\004CAR8\022\002\010\002\n\n\n\004CAR9\022\002\010\002\022\026\n\004lscc\022\016\n\014\n\006fabcar\022\002\010\001\032\241\007\010\310\001\032\233\007[{\"Key\":\"CAR0\", \"Record\":{\"colour\":\"blue\",\"make\":\"Toyota\",\"model\":\"Prius\",\"owner\":\"Tomoko\"}},{\"Key\":\"CAR1\", \"Record\":{\"colour\":\"red\",\"make\":\"Ford\",\"model\":\"Mustang\",\"owner\":\"Brad\"}},{\"Key\":\"CAR2\", \"Record\":{\"colour\":\"green\",\"make\":\"Hyundai\",\"model\":\"Tucson\",\"owner\":\"Jin Soo\"}},{\"Key\":\"CAR3\", \"Record\":{\"colour\":\"yellow\",\"make\":\"Volkswagen\",\"model\":\"Passat\",\"owner\":\"Max\"}},{\"Key\":\"CAR4\", \"Record\":{\"colour\":\"black\",\"make\":\"Tesla\",\"model\":\"S\",\"owner\":\"Adriana\"}},{\"Key\":\"CAR5\", \"Record\":{\"colour\":\"purple\",\"make\":\"Peugeot\",\"model\":\"205\",\"owner\":\"Michel\"}},{\"Key\":\"CAR6\", \"Record\":{\"colour\":\"white\",\"make\":\"Chery\",\"model\":\"S22L\",\"owner\":\"Aarav\"}},{\"Key\":\"CAR7\", \"Record\":{\"colour\":\"violet\",\"make\":\"Fiat\",\"model\":\"Punto\",\"owner\":\"Pari\"}},{\"Key\":\"CAR8\", \"Record\":{\"colour\":\"indigo\",\"make\":\"Tata\",\"model\":\"Nano\",\"owner\":\"Valeria\"}},{\"Key\":\"CAR9\", \"Record\":{\"colour\":\"brown\",\"make\":\"Holden\",\"model\":\"Barina\",\"owner\":\"Shotaro\"}}]\"\r\022\006fabcar\032\0031.0" endorsement:<endorser:"\n\007Org1MSP\022\200\006-----BEGIN -----\nMIICGjCCAcCgAwIBAgIRAPlwF/rUZUP9mqN4wSml4iswCgYIKoZIzj0EAwIwczEL\nMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG\ncmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh\nLm9yZzEuZXhhbXBsZS5jb20wHhcNMTcwODMxMDkxNDMyWhcNMjcwODI5MDkxNDMy\nWjBbMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN\nU2FuIEZyYW5jaXNjbzEfMB0GA1UEAxMWcGVlcjAub3JnMS5leGFtcGxlLmNvbTBZ\nMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHihxW6ks3B2+5XdbAVq3CBgxRRRZ22x\nzzpqnD86nKkz7fBElBuhlXl2K6rTxyY2OBOB0ts8keqZ93xueRGymrajTTBLMA4G\nA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMCsGA1UdIwQkMCKAIEI5qg3Ndtru\nuLoM2nAYUdFFBNMarRst3dusalc2Xkl8MAoGCCqGSM49BAMCA0gAMEUCIQD4j0Rn\ne1rrd0FSCzsR6u+IuuPK5dI/kR/bh7+VLf0TNgIgCfUtkJvfvzVEwZLFoFyjoHtr\ntvwzNUS1U0hEqIaDeo4=\n-----END -----\n" signature:"0E\002!\000\347C\027\336\315\262`\213\3647\314=6\244b'\217vl\322\304\272\010\275\205w\365\\q\362%X\002 \t\333_\241\346op\271[\253\034g\272n-\020\027\265\261\276\030\371TA\246:[_\021\020%^" >
2018-03-02 08:46:06.852 UTC [chaincodeCmd] chaincodeInvokeOrQuery -> INFO 00a Chaincode invoke successful. result: status:200 payload:"[{\"Key\":\"CAR0\", \"Record\":{\"colour\":\"blue\",\"make\":\"Toyota\",\"model\":\"Prius\",\"owner\":\"Tomoko\"}},{\"Key\":\"CAR1\", \"Record\":{\"colour\":\"red\",\"make\":\"Ford\",\"model\":\"Mustang\",\"owner\":\"Brad\"}},{\"Key\":\"CAR2\", \"Record\":{\"colour\":\"green\",\"make\":\"Hyundai\",\"model\":\"Tucson\",\"owner\":\"Jin Soo\"}},{\"Key\":\"CAR3\", \"Record\":{\"colour\":\"yellow\",\"make\":\"Volkswagen\",\"model\":\"Passat\",\"owner\":\"Max\"}},{\"Key\":\"CAR4\", \"Record\":{\"colour\":\"black\",\"make\":\"Tesla\",\"model\":\"S\",\"owner\":\"Adriana\"}},{\"Key\":\"CAR5\", \"Record\":{\"colour\":\"purple\",\"make\":\"Peugeot\",\"model\":\"205\",\"owner\":\"Michel\"}},{\"Key\":\"CAR6\", \"Record\":{\"colour\":\"white\",\"make\":\"Chery\",\"model\":\"S22L\",\"owner\":\"Aarav\"}},{\"Key\":\"CAR7\", \"Record\":{\"colour\":\"violet\",\"make\":\"Fiat\",\"model\":\"Punto\",\"owner\":\"Pari\"}},{\"Key\":\"CAR8\", \"Record\":{\"colour\":\"indigo\",\"make\":\"Tata\",\"model\":\"Nano\",\"owner\":\"Valeria\"}},{\"Key\":\"CAR9\", \"Record\":{\"colour\":\"brown\",\"make\":\"Holden\",\"model\":\"Barina\",\"owner\":\"Shotaro\"}}]"
2018-03-02 08:46:06.852 UTC [main] main -> INFO 00b Exiting.....

```

**Comment by fifahuihua** [comment]
Finally, I resolved it myself! I was caused by my local proxy, I disabled my local proxy, and then **REOPEN the terminal** and execute "node query.js" it works!!!.

**Comment by Mihara17** [comment]
cool fifahuihua

**Comment by jle-quel** [comment]
@fifahuihua Could you be more specific about the disabling of the local Proxy?

**Comment by fifahuihua** [comment]
@jle-quel  
I just disabled my local proxy settings in .bashrc file.
`# http_proxy=proxyaddress:port` 
Like as comment above line.
