### ISSUE TITLE
Error while Instantiating the chain code

### ISSUE THREAD

**Issue by aakkss11** [IBM-Blockchain-Archive/marbles#212]
on giving command: 
cd ./scripts
node install_chaincode.js
I am getting below error. 
Error: First we enroll
/home/anant/marbles/utils/connection_profile_lib/parts/org.js:91
                    throw new Error('Admin private key is not found in the creds json file: ' + orgName);
                    ^

Error: Admin private key is not found in the creds json file: Org1MSP
    at Object.helper.getAdminPrivateKeyPEM (/home/anant/marbles/utils/connection_profile_lib/parts/org.js:91:12)
    at Object.cp.makeEnrollmentOptionsUsingCert (/home/anant/marbles/utils/connection_profile_lib/index.js:238:22)
    at Object.<anonymous> (/home/anant/marbles/scripts/install_chaincode.js:42:28)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)

**Comment by dshuffma-ibm** [comment]
try the amended [readme/docs](https://github.com/IBM-Blockchain/marbles/blob/master/docs/install_chaincode_locally.md#get-crypto-material) (option 1 if you are using a local hyperledger fabric network).

you likely still need to run the `node enrollAdmin.js`  and `node registerUser.js` commands from `fabcar`.

**Comment by tuyt-ch** [comment]
same here,
already run the `node enrollAdmin.js` and `node registerUser.js` commands from `fabcar`. but still getting: 
```
info: First we enroll
/home/hl/code/marbles/utils/connection_profile_lib/parts/org.js:102
		throw new Error('Cannot find org.', orgName);
		^

Error: Cannot find org.
    at Object.helper.getAdminPrivateKeyPEM (/home/hl/code/marbles/utils/connection_profile_lib/parts/org.js:102:9)
    at Object.cp.makeEnrollmentOptionsUsingCert (/home/hl/code/marbles/utils/connection_profile_lib/index.js:238:22)
    at Object.<anonymous> (/home/hl/code/marbles/scripts/install_chaincode.js:42:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

**Comment by madanuuk2** [comment]
I have solved it in the following way.

Pls try any one of the following to solve the above 'node install_chaincode.js' error :

1. Make sure that the 'fabric-samples' folder is immediately inside the $HOME folder
2. If your 'fabric-samples' is located at some other place, make the path changes accordingly in the file 'marbles/config/connection_profile_local.json' at the lines 10, 39 and 42.

Hope it helps !

**Comment by tuyt-ch** [comment]
@madanuuk2 thank you, after adjusting the config file it worked like a charm 👍
