### ISSUE TITLE
ubuntu

### ISSUE THREAD

**Issue by lilinkai** [IBM-Blockchain-Archive/marbles#215]
root@parallels-vm:~/fabric-samples/fabcar# node enrollAdmin.js
/home/parallels/fabric-samples/fabcar/node_modules/grpc/src/grpc_extension.js:55
    throw error;
    ^

Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v57-linux-x64-glibc
Found: [node-v46-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/parallels/fabric-samples/fabcar/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/home/parallels/fabric-samples/fabcar/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/parallels/fabric-samples/fabcar/node_modules/grpc/src/client.js:37:12)
    at Module._compile (module.js:652:30)

**Comment by YoleYu** [comment]
node 依赖包没安装完整，检查是否运行过npm install, 或者运行的时候是否有错误。

**Comment by mrshah-at-work** [comment]
@lilinkai @YoleYu this repository does not deal with fabcar, it only deals with Marbles. Please reopen if you think this issue is related to Marbles.
