### ISSUE TITLE
Error in "gulp marbles_local"

### ISSUE THREAD

**Issue by c1ick** [IBM-Blockchain-Archive/marbles#218]
I Flow the step in Host Marbles Locally

and I excute 

>gulp marbles_local 

~~~
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

~~~

and i find the fs.js

~~~
/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/protobufjs/externs/fs.js
/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js
/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/graceful-fs/fs.js
/home/vagrant/go/src/github.com/hyperledger/marbles/node_modules/grpc/node_modules/graceful-fs/fs.js
/home/vagrant/go/src/github.com/hyperledger/fabric-samples/fabcar/node_modules/protobufjs/externs/fs.js
/home/vagrant/go/src/github.com/hyperledger/fabric-samples/fabcar/node_modules/graceful-fs/fs.js
/home/vagrant/go/src/github.com/hyperledger/fabric-samples/fabcar/node_modules/grpc/node_modules/graceful-fs/fs.js

~~~

what can I do to solve this problem?

**Comment by dshuffma-ibm** [comment]
npm did not install `node-sass` correctly.  try deleting the `marbles/node_modules/` folder and re-running `npm install`.  look at the console logs, it should contain no errors.

**Comment by c1ick** [comment]
Thx! 
@dshuffma-ibm

it works.!!!!!
have a good day!
