### ISSUE TITLE
Error: Cannot find org.

### ISSUE THREAD

**Issue by zhuimengshaonian66** [IBM-Blockchain-Archive/marbles#219]
tsinghua-yincheng@QQ475318423:~/桌面/app/marbles/scripts$ node install_chaincode.js
info: Loaded config file /home/tsinghua-yincheng/桌面/app/marbles/config/marbles_local.json
info: Loaded connection profile file /home/tsinghua-yincheng/桌面/app/marbles/config/connection_profile_local.json

Connection Profile Lib Functions:()
  getNetworkName()
  getNetworkCredFileName()
  buildTlsOpts()
  getFirstChannelId()
  getChannelId()
  loadPem()
  getMarblesField()
  getChaincodeId()
  getChaincodeVersion()
  getFirstCaName()
  getCA()
  getCasUrl()
  getAllCaUrls()
  getCaName()
  getCaTlsCertOpts()
  getEnrollObj()
  getFirstPeerName()
  getPeer()
  getPeersUrl()
  getAllPeerUrls()
  getPeerEventUrl()
  getPeerTlsCertOpts()
  getMarbleUsernamesConfig()
  getCompanyNameFromFile()
  getMarblesPort()
  getEventsSetting()
  getKeepAliveMs()
  getFirstOrdererName()
  getOrderer()
  getOrderersUrl()
  getOrdererTlsCertOpts()
  getBlockDelay()
  getKvsPath()
  getFirstOrg()
  getClientsOrgName()
  getClientOrg()
  getMarbleUsernames()
  getOrgsMSPid()
  getAdminPrivateKeyPEM()
  getAdminSignedCertPEM()
---------------------------------------
info: Lets install some chaincode - marbles v4
---------------------------------------
info: First we enroll
/home/tsinghua-yincheng/桌面/app/marbles/utils/connection_profile_lib/parts/org.js:102
		throw new Error('Cannot find org.', orgName);
		^

Error: Cannot find org.
    at Object.helper.getAdminPrivateKeyPEM (/home/tsinghua-yincheng/桌面/app/marbles/utils/connection_profile_lib/parts/org.js:102:9)
    at Object.cp.makeEnrollmentOptionsUsingCert (/home/tsinghua-yincheng/桌面/app/marbles/utils/connection_profile_lib/index.js:238:22)
    at Object.<anonymous> (/home/tsinghua-yincheng/桌面/app/marbles/scripts/install_chaincode.js:42:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

i cant solve it   so sad

**Comment by mrshah-at-work** [comment]
Ref: https://github.com/IBM-Blockchain/marbles/issues/217#issuecomment-385162926

**Comment by huaizhuang700** [comment]
Hello, can you solve this problem?
