### ISSUE TITLE
Caught exception:  TypeError: Cannot read property 'getConnectivityState' of undefined

### ISSUE THREAD

**Issue by yangmiok** [IBM-Blockchain-Archive/marbles#220]
error: Caught exception:  TypeError: Cannot read property 'getConnectivityState' of undefined
    at _checkConnection (/root/fabric-samples/marbles/node_modules/fabric-client/lib/EventHub.js:471:38)
    at registerTxEvent (/root/fabric-samples/marbles/node_modules/fabric-client/lib/EventHub.js:713:8)
    at setup_event_hub (/root/fabric-samples/marbles/utils/fc_wrangler/parts/invoke_cc.js:125:14)
    at Object.invoke_cc.invoke_chaincode (/root/fabric-samples/marbles/utils/fc_wrangler/parts/invoke_cc.js:52:3)
    at Object.fcw.invoke_chaincode (/root/fabric-samples/marbles/utils/fc_wrangler/index.js:57:13)
    at Object.marbles_chaincode.register_owner (/root/fabric-samples/marbles/utils/marbles_cc_lib.js:230:7)
    at Object.startup_lib.create_owners (/root/fabric-samples/marbles/utils/startup_lib.js:260:15)
    at /root/fabric-samples/marbles/utils/startup_lib.js:211:17
    at /root/fabric-samples/marbles/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/root/fabric-samples/marbles/node_modules/async/dist/async.js:1003:9)
debug: [ws] broadcasting to clients.  1 error
error: Caught exception:  TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/root/fabric-samples/marbles/node_modules/fabric-client/lib/EventHub.js:305:55)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:130:10)
    at Object.onReceiveMessage (/root/fabric-samples/marbles/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/root/fabric-samples/marbles/node_modules/grpc/src/client_interceptors.js:629:19)
    at /root/fabric-samples/marbles/node_modules/grpc/src/client_interceptors.js:728:14
debug: [ws] broadcasting to clients.  1 error

**Comment by lasreeram** [comment]
I am getting exactly the same error. The setup steps 1, 2 3 work correctly. I get this on Step 4 when the first marble (amy) is being created.

**Comment by dshuffma-ibm** [comment]
so the grpc module v1.11.0 is not compatible with the older v1.10.0 interface...  the SDK is pulling in v1.11.0.  to fix it I've added a specific version of grpc in package.json.  https://github.com/IBM-Blockchain/marbles/commit/964d08d7b474f7650a2f8bafe2c9d97dd7c85fd2 

if you have already ran into this error, you will need to uninstall grpc before you reinstall. `npm uinstall grpc`, then you can pull in the changes and `npm install`.

**Comment by lasreeram** [comment]
That worked. Thanks!

**Comment by lwy599** [comment]
Currently I am getting this error even though the grpc module is v1.10.1:
info: Creating a marble owner...
debug: [fcw] setting target event url grpc://localhost:7053
debug: [fcw] Invoking Chaincode: init_owner()
debug: [fcw] Sending invoke req chaincodeId=marbles, fcn=init_owner, args=[o01527515931064nsYGJ, amy, United Marbles], 0=193, 1=51, 2=196, 3=93, 4=149, 5=89, 6=216, 7=29, 8=156, 9=44, 10=76, 11=174, 12=252, 13=138, 14=135, 15=75, 16=57, 17=41, 18=95, 19=67, 20=209, 21=133, 22=192, 23=35, _transaction_id=41c7da72279f94af6d2b29d358dee51df83520758de73c6d864e118f9a4726d8
debug: [fcw] listening to transaction event. url: grpc://localhost:7053
info: [EventHub.js]: _connect - options {"grpc.http2.keepalive_time":300,"grpc.keepalive_time_ms":300000,"grpc.http2.keepalive_timeout":35,"grpc.keepalive_timeout_ms":3500,"grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
error: Caught exception:  TypeError: Cannot read property 'getConnectivityState' of undefined
    at EventHub._checkConnection (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/lib/EventHub.js:471:39)
    at EventHub.registerTxEvent (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/lib/EventHub.js:713:8)
    at setup_event_hub (/home/lwy599/IBM_Bluemix/adcoin/utils/fc_wrangler/parts/invoke_cc.js:125:14)
    at Object.invoke_cc.invoke_chaincode (/home/lwy599/IBM_Bluemix/adcoin/utils/fc_wrangler/parts/invoke_cc.js:52:3)
    at Object.fcw.invoke_chaincode (/home/lwy599/IBM_Bluemix/adcoin/utils/fc_wrangler/index.js:57:13)
    at Object.marbles_chaincode.register_owner (/home/lwy599/IBM_Bluemix/adcoin/utils/marbles_cc_lib.js:230:7)
    at Object.startup_lib.create_owners (/home/lwy599/IBM_Bluemix/adcoin/utils/startup_lib.js:260:15)
    at /home/lwy599/IBM_Bluemix/adcoin/utils/startup_lib.js:211:17
    at /home/lwy599/IBM_Bluemix/adcoin/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/home/lwy599/IBM_Bluemix/adcoin/node_modules/async/dist/async.js:1003:9)
debug: [ws] broadcasting to clients.  1 error
debug: [ws] broadcasting to clients.  2 error
debug: [ws] broadcasting to clients.  3 error
debug: [ws] broadcasting to clients.  4 error
error: Caught exception:  TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/lib/EventHub.js:305:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:629:19)
    at /home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:728:14
debug: [ws] broadcasting to clients.  1 error
debug: [ws] broadcasting to clients.  2 error
debug: [ws] broadcasting to clients.  3 error
debug: [ws] broadcasting to clients.  4 error

**Comment by macinjoke** [comment]
I faced the same issue. 
But resolved by https://github.com/IBM-Blockchain/marbles/issues/229#issuecomment-394428802 .
I don't know why.
