### ISSUE TITLE
Error: Missing parameter. Must have a username

### ISSUE THREAD

**Issue by thilakg** [IBM-Blockchain-Archive/marbles#224]
Hi All,

I am new to block chain and hyperledger-fabric, I am trying to setup Marbles sample application. I followed tutorial [Use Local Hyperledger Network](https://github.com/IBM-Blockchain/marbles/blob/master/docs/use_local_hyperledger.md).

While executing this command (node enrollAdmin.js) i got following error.
Node version   :   v6.2.1
Npm Version    :   3.9.3
Docker Version:  18.03.1-ce

`$ node enrollAdmin.js`
```
 Store path:/opt/blockchain/fabric-samples/fabcar/hfc-key-store
 Successfully enrolled admin user "admin"
error: [Client.js]: Error: Missing parameter. Must have a username.
    at _setUserFromConfig (/opt/blockchain/fabric-samples/fabcar/node_modules/fabric-client/lib/Client.js:1280:27)
    at Promise (/opt/blockchain/fabric-samples/fabcar/node_modules/fabric-client/lib/Client.js:1432:11)
    at setUserContext (/opt/blockchain/fabric-samples/fabcar/node_modules/fabric-client/lib/Client.js:1413:10)
    at promise.then.then.then.then (/opt/blockchain/fabric-samples/fabcar/node_modules/fabric-client/lib/Client.js:1692:17)
Error: Failed to load key or certificate and save to local stores.
    at promise.then.then.then.then.then.catch (/opt/blockchain/fabric-samples/fabcar/node_modules/fabric-client/lib/Client.js:1702:19)
Failed to enroll admin: Error: Failed to enroll admin
```

Could anyone help me to resolve this error?

Thanks in advance.

**Comment by thilakg** [comment]
It got worked when i ran the following command

`$ sudo node enrollAdmin.js`
