### ISSUE TITLE
Can`t install the chaincode

### ISSUE THREAD

**Issue by thiagochiaro** [IBM-Blockchain-Archive/marbles#227]
Everything is going fine but I can't install the chaincode. I already tried changing npm permissions but it didn't help and this message error keeps popping up. Any idea what is the problem?

:`~/marbles/scripts$ node install_chaincode.js`
info: Loaded config file /home/thiago/marbles/config/marbles_local.json
internal/modules/cjs/loader.js:676
    throw err;
    ^

SyntaxError: /home/thiago/marbles/config/connection_profile_local.json: Unexpected token ' in JSON at position 278
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:673:27)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at module.exports (/home/thiago/marbles/utils/connection_profile_lib/index.js:38:14)
    at Object.<anonymous> (/home/thiago/marbles/scripts/install_chaincode.js:34:83)
    at Module._compile (internal/modules/cjs/loader.js:654:30)

**Comment by github-harry** [comment]
I think there is a syntax error like invalid character or miss-matching '{' '}'. 
It is better to check it using json formatter like "https://jsonformatter.curiousconcept.com"

**Comment by dshuffma-ibm** [comment]
closing, inactivity
