### ISSUE TITLE
Caught exception: TypeError: Cannot read property 'getConnectivityState' of undefined

### ISSUE THREAD

**Issue by lwy599** [IBM-Blockchain-Archive/marbles#229]
Currently I am getting this error even though the grpc module is v1.10.1:
info: Creating a marble owner...
debug: [fcw] setting target event url grpc://localhost:7053
debug: [fcw] Invoking Chaincode: init_owner()
debug: [fcw] Sending invoke req chaincodeId=marbles, fcn=init_owner, args=[o01527515931064nsYGJ, amy, United Marbles], 0=193, 1=51, 2=196, 3=93, 4=149, 5=89, 6=216, 7=29, 8=156, 9=44, 10=76, 11=174, 12=252, 13=138, 14=135, 15=75, 16=57, 17=41, 18=95, 19=67, 20=209, 21=133, 22=192, 23=35, _transaction_id=41c7da72279f94af6d2b29d358dee51df83520758de73c6d864e118f9a4726d8
debug: [fcw] listening to transaction event. url: grpc://localhost:7053
info: [EventHub.js]: _connect - options {"grpc.http2.keepalive_time":300,"grpc.keepalive_time_ms":300000,"grpc.http2.keepalive_timeout":35,"grpc.keepalive_timeout_ms":3500,"grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
error: Caught exception: TypeError: Cannot read property 'getConnectivityState' of undefined
at EventHub._checkConnection (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/lib/EventHub.js:471:39)
at EventHub.registerTxEvent (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/lib/EventHub.js:713:8)
at setup_event_hub (/home/lwy599/IBM_Bluemix/adcoin/utils/fc_wrangler/parts/invoke_cc.js:125:14)
at Object.invoke_cc.invoke_chaincode (/home/lwy599/IBM_Bluemix/adcoin/utils/fc_wrangler/parts/invoke_cc.js:52:3)
at Object.fcw.invoke_chaincode (/home/lwy599/IBM_Bluemix/adcoin/utils/fc_wrangler/index.js:57:13)
at Object.marbles_chaincode.register_owner (/home/lwy599/IBM_Bluemix/adcoin/utils/marbles_cc_lib.js:230:7)
at Object.startup_lib.create_owners (/home/lwy599/IBM_Bluemix/adcoin/utils/startup_lib.js:260:15)
at /home/lwy599/IBM_Bluemix/adcoin/utils/startup_lib.js:211:17
at /home/lwy599/IBM_Bluemix/adcoin/node_modules/async/dist/async.js:3083:16
at eachOfArrayLike (/home/lwy599/IBM_Bluemix/adcoin/node_modules/async/dist/async.js:1003:9)
debug: [ws] broadcasting to clients. 1 error
debug: [ws] broadcasting to clients. 2 error
debug: [ws] broadcasting to clients. 3 error
debug: [ws] broadcasting to clients. 4 error
error: Caught exception: TypeError: Cannot read property 'getConnectivityState' of undefined
at ClientDuplexStream. (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/lib/EventHub.js:305:56)
at emitOne (events.js:116:13)
at ClientDuplexStream.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
at Object.onReceiveMessage (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1302:19)
at InterceptingListener.recvMessageWithContext (/home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:629:19)
at /home/lwy599/IBM_Bluemix/adcoin/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:728:14
debug: [ws] broadcasting to clients. 1 error
debug: [ws] broadcasting to clients. 2 error
debug: [ws] broadcasting to clients. 3 error
debug: [ws] broadcasting to clients. 4 error

The setup steps 1, 2 3 work correctly. I get this on Step 4 when the first marble (amy) is being created. 
I am at the latest commit.

**Comment by dshuffma-ibm** [comment]
as a work around you could try not using eventhub, change `use_events` to `false` https://github.com/IBM-Blockchain/marbles/blob/master/config/marbles_local.json#L3 .

**Comment by dshuffma-ibm** [comment]
closing, inactivity

**Comment by nyetwurk** [comment]
Why did you close this bug? It is clearly still there.

**Comment by dshuffma-ibm** [comment]
@nyetwurk 
>closing, inactivity

I closed it because inactivity.

I've been unable to reproduce this and OP vanished. No one else has reached out with a similar issue.

**Comment by nyetwurk** [comment]
Sorry, I meant that the suggested solution of simply using an ancient version of grpc is not optimal. The code should be fixed to support recent versions.

**Comment by abdussamad007** [comment]
I am experiencing the same.. 
 I followed the steps in https://github.com/IBM-Blockchain/marbles/blob/master/README.md#3-install-and-instantiate-chaincode

debug: [fcw] listening to transaction event. url: grpc://localhost:7053
info: [EventHub.js]: _connect - options {"grpc.http2.keepalive_time":300,"grpc.keepalive_time_ms":300000,"grpc.http2.keepalive_timeout":35,"grpc.keepalive_timeout_ms":3500,"grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
error: Caught exception:  TypeError: Cannot read property 'getConnectivityState' of undefined
    at EventHub._checkConnection (/home/abdus/fabric-samples/marbles/node_modules/fabric-client/lib/EventHub.js:471:39)
    at EventHub.registerTxEvent (/home/abdus/fabric-samples/marbles/node_modules/fabric-client/lib/EventHub.js:713:8)
    at setup_event_hub (/home/abdus/fabric-samples/marbles/utils/fc_wrangler/parts/invoke_cc.js:125:14)
    at Object.invoke_cc.invoke_chaincode (/home/abdus/fabric-samples/marbles/utils/fc_wrangler/parts/invoke_cc.js:52:3)
    at Object.fcw.invoke_chaincode (/home/abdus/fabric-samples/marbles/utils/fc_wrangler/index.js:57:13)
    at Object.marbles_chaincode.register_owner (/home/abdus/fabric-samples/marbles/utils/marbles_cc_lib.js:230:7)
    at Object.startup_lib.create_owners (/home/abdus/fabric-samples/marbles/utils/startup_lib.js:260:15)
    at /home/abdus/fabric-samples/marbles/utils/startup_lib.js:211:17
    at /home/abdus/fabric-samples/marbles/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/home/abdus/fabric-samples/marbles/node_modules/async/dist/async.js:1003:9)
debug: [ws] broadcasting to clients.  1 error
debug: [ws] broadcasting to clients.  2 error
error: Caught exception:  TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/abdus/fabric-samples/marbles/node_modules/fabric-client/lib/EventHub.js:305:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/abdus/fabric-samples/marbles/node_modules/grpc/src/client_interceptors.js:1292:19)
    at InterceptingListener.recvMessageWithContext (/home/abdus/fabric-samples/marbles/node_modules/grpc/src/client_interceptors.js:607:19)
    at /home/abdus/fabric-samples/marbles/node_modules/grpc/src/client_interceptors.js:706:14
debug: [ws] broadcasting to clients.  1 error
debug: [ws] broadcasting to clients.  2 error
debug: [fcw] Querying Channel Stats
debug: [fcw] Querying Channel Stats
Any idea?
