### ISSUE TITLE
Problem running gulp marbles_tls

### ISSUE THREAD

**Issue by sctan88** [IBM-Blockchain-Archive/marbles#240]
Hi there,

I kept getting the following error when running "gulp marbles_tls" command. Do you know what step I have missed? I have ran npm install gulp -g and npm install commands and also modified the connection_profile_tls.json file with the connection profile copied.

```
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/etan128/Projects/ibm_cloud_platform/marbles/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/etan128/Projects/ibm_cloud_platform/marbles/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/Users/etan128/Projects/ibm_cloud_platform/marbles/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/etan128/Projects/ibm_cloud_platform/marbles/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/etan128/Projects/ibm_cloud_platform/marbles/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/etan128/Projects/ibm_cloud_platform/marbles/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/etan128/Projects/ibm_cloud_platform/marbles/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

cheers
Estee

**Comment by dshuffma-ibm** [comment]
`node-sass` did not install correctly,  try again with the command `npm install` or maybe `sudo npm install`.  

ideally you don't see any read text.

**Comment by sctan88** [comment]
Yes, got it working. Thanks

**Comment by dshuffma-ibm** [comment]
closing, inactivity
