### ISSUE TITLE
Error occured when running "node install_chaincode.js"

### ISSUE THREAD

**Issue by offthewall123** [IBM-Blockchain-Archive/marbles#247]
Error occured when running this command  
error message as follow 

/Users/xu/Desktop/marbles/node_modules/grpc/src/grpc_extension.js:57
    throw e;
    ^

Error: dlopen(/Users/xu/Desktop/marbles/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node, 1): no suitable image found.  Did find:
	/Users/xu/Desktop/marbles/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node: truncated mach-o error: segment __TEXT extends to 606208 which is past end of file 39936
	/Users/xu/Desktop/marbles/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node: truncated mach-o error: segment __TEXT extends to 606208 which is past end of file 39936
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xu/Desktop/marbles/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by CiroGamboa** [comment]
How did you solve it?
