### ISSUE TITLE
ERROR : sendPeersProposal - Promise is rejected

### ISSUE THREAD

**Issue by Jayaramdas2002** [IBM-Blockchain-Archive/marbles#258]
# gulp marbles_local gives me the following error

error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/root/marbles/node_modules/grpc/src/client.js:64:15)
    at /root/marbles/node_modules/grpc/src/client.js:583:15
warn: [fcw] warning - query resp is not json, might be okay: string Error: 14 UNAVAILABLE: Connect Failed

Kindly suggest how to solve this issue.

**Comment by dshuffma-ibm** [comment]
https://github.com/IBM-Blockchain/marbles/issues/200

**Comment by Jayaramdas2002** [comment]
I have followed the process but node query.js generated following error

Store path:/root/marbles/fabric-samples/fabcar/hfc-key-store
Successfully loaded user1 from persistence
Failed to query successfully :: Error: "targets" parameter not specified and no peers are set on this Channel instance or specfied for this channel in the network

**Comment by dshuffma-ibm** [comment]
Missing `targets` could happen for a few reasons.  First to check is if you actually have peers defined in your config JSON file.  Second is if the `fcw` code was able to find these peers and parse them.  Third is if the SDK is getting the peer target fields or not. There should be more logs to help you figure out where to start.  

this file might be a good place to start looking: https://github.com/IBM-Blockchain/marbles/blob/master/utils/marbles_cc_lib.js  you need to see the logs to figure out which function is being called. then look at the `peer_urls` fields and see if its blank.  track it backwards to figure out what is going on.
