### ISSUE TITLE
throw new errors.AssertionError when run gulp marbles_local

### ISSUE THREAD

**Issue by BruceOwen** [IBM-Blockchain-Archive/marbles#264]
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/root/gopath/src/github.com/hyperledger/fabric/examples/marbles/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/root/gopath/src/github.com/hyperledger/fabric/examples/marbles/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/root/gopath/src/github.com/hyperledger/fabric/examples/marbles/gulpfile.js:29:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by dshuffma-ibm** [comment]
What version of node are you running and what OS are you on? You may want to reinstall/start clean.

**Comment by cimoko** [comment]
It is caused by the version of gulp. You can use the command "gulp -v" to check the version in your local. 
and you should change the version to 3.9.1.

**Comment by dshuffma-ibm** [comment]
closing - inactivity
