### ISSUE TITLE
how to config two org in local or tls?

### ISSUE THREAD

**Issue by Matthewbalala** [IBM-Blockchain-Archive/marbles#275]
i config two org, but have something wrong.

error: [fcw] Failed to get enrollment marbleswwwwwwOrg1MSPOrg2MSPpeer0org1examplecom Error: Illegal value for Message.Field .msp.SerializedIdentity.mspid of type string: object (no array expected)
    at fail (/home/batista/marbles/node_modules/protobufjs/dist/protobuf.js:3465:23)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/batista/marbles/node_modules/protobufjs/dist/protobuf.js:3497:17)
    at Message.setter (/home/batista/marbles/node_modules/protobufjs/dist/protobuf.js:2582:77)
    at Identity.serialize (/home/batista/marbles/node_modules/fabric-client/lib/msp/identity.js:113:22)
    at new TransactionID (/home/batista/marbles/node_modules/fabric-client/lib/TransactionID.js:49:49)
    at Channel.queryByChaincode (/home/batista/marbles/node_modules/fabric-client/lib/Channel.js:1557:14)
    at Object.query_cc.query_chaincode (/home/batista/marbles/utils/fc_wrangler/parts/query_cc.js:31:11)
    at Object.fcw.query_chaincode (/home/batista/marbles/utils/fc_wrangler/index.js:91:12)
    at Object.marbles_chaincode.check_if_already_instantiated (/home/batista/marbles/utils/marbles_cc_lib.js:29:7)
    at Object.startup_lib.setup_marbles_lib (/home/batista/marbles/utils/startup_lib.js:143:15)
error: [fcw] could not format error
info: Retrying enrollment on different ca
info: [fcw] Going to enroll peer_urls=[grpcs://192.168.63.132:7050], channel_id=www, uuid=marbleswwwwwwOrg1MSPOrg2MSPpeer0org1examplecom, ca_url=https://192.168.63.132:8050, orderer_url=grpcs://192.168.63.132:7550, enroll_id=admin, enroll_secret=adminpw, msp_id=[Org1MSP, Org2MSP], kvs_path=/home/batista/.hfc-key-store/marbleswwwwwwOrg1MSPOrg2MSPpeer0org1examplecom
warn: [fcw] The msp id in KVS does not match the msp id passed to enroll. Need to clear the KVS. [ 'Org1MSP', 'Org2MSP' ] 0=Org1MSP, 1=Org2MSP
error: [fcw] MSP in KVS mismatch. KVS has been deleted. Restart the app to try again.

**Comment by dshuffma-ibm** [comment]
not quite enough info to go on.  can you upload your config files in a zip?
