### ISSUE TITLE
glup marbles_local excution error

### ISSUE THREAD

**Issue by ghost** [IBM-Blockchain-Archive/marbles#281]
----------------------------------- Server Up - localhost:3001 -----------------------------------
Welcome aboard:	 United Marbles
Channel:	         mychannel
Org:		         Org1MSP
CA:		                 fabric-ca
Orderer:	                 fabric-orderer
Peer:		         fabric-peer-org1
Chaincode ID:	 marbles
Chaincode Version:  v4
------------------------------------------ Websocket Up ------------------------------------------

info: [fcw] Going to enroll peer_urls=[grpc://dailylabdev.iptime.org:7051], channel_id=mychannel, uuid=marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1, ca_url=dailylabdev.iptime.org:7054, orderer_url=grpc://dailylabdev.iptime.org:7050, enroll_id=admin, enroll_secret=adminpw, msp_id=Org1MSP, kvs_path=/home/daily/Desktop/hyper/marbles/fabric-samples/fabcar/hfc-key-store
error: [Client.js]: Failed to load user "admin" from local key value store. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/daily/Desktop/hyper/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [Client.js]: Failed to load an instance of requested user "admin" from the state store on this Client instance. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/daily/Desktop/hyper/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] Failed to get enrollment marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1 Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/daily/Desktop/hyper/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] could not format error
error: Exhausted all CAs. There are no more CAs to try.
error: could not enroll...
warn: removing older kvs and trying to enroll again
warn: removed older kvs
info: [fcw] Going to enroll peer_urls=[grpc://dailylabdev.iptime.org:7051], channel_id=mychannel, uuid=marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1, ca_url=dailylabdev.iptime.org:7054, orderer_url=grpc://dailylabdev.iptime.org:7050, enroll_id=admin, enroll_secret=adminpw, msp_id=Org1MSP, kvs_path=/home/daily/Desktop/hyper/marbles/fabric-samples/fabcar/hfc-key-store
error: [Client.js]: Failed to load user "admin" from local key value store. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/daily/Desktop/hyper/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [Client.js]: Failed to load an instance of requested user "admin" from the state store on this Client instance. Error: Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/daily/Desktop/hyper/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] Failed to get enrollment marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1 Error: Private key missing from key store. Can not establish the signing identity for user admin
    at _cryptoSuite.importKey.then.then (/home/daily/Desktop/hyper/marbles/node_modules/fabric-client/lib/User.js:255:11)
    at <anonymous>
error: [fcw] could not format error
error: Exhausted all CAs. There are no more CAs to try.
error: could not enroll...
warn: Error enrolling admin

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
info: Detected that we have NOT launched successfully yet
debug: Open your browser to http://localhost:3001 and login as "admin" to initiate startup
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I use script code in "/marbles/fabric-sample/fabcar/javascript-low-level/"

and this scripts made 'hfc-key-store' directory and save some key files.

so i copied this directory to "/marbles/fabric-sample/fabcar/hfc-key-store"
(First time, there is no directory "hfc-key-store" in 'fabcar') 

and change "/marbles/config/connection_profile_local.json" and then i use 'install_chaincode.js' and 'instance_chaincode.js'
(the all path value is valid, there is a some key files and key-store directory)

last time, i run "glup marbles_local"

but error occur 

Need help..

**Comment by dshuffma-ibm** [comment]
are you beyond this issue? I see that you opened #282, which is farther in the startup process.

the first error `Error: Error: Private key missing from key store` is telling you it can't find the private key that should be already setup.  you should look for the files yourself and see if the path to them is correct.  the path that Marbles is using is [here](https://github.com/IBM-Blockchain/marbles/blob/master/config/connection_profile_local.json#L10)

**Comment by mfaisaltariq** [comment]
@Daily-Sim can you please post the solution how did you solve the above problem. Thank you.
