### ISSUE TITLE
peer.js not found..

### ISSUE THREAD

**Issue by kuldeept70** [IBM-Blockchain-Archive/marbles#283]
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'fabric-client/lib/Peer.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (C:\Users\Kuldeep Raj Tiwari\Desktop\Marbles Example\marbles\utils\fc_wrangler\parts\query_peer.js:9:13)
    at module.exports (C:\Users\Kuldeep Raj Tiwari\Desktop\Marbles Example\marbles\utils\fc_wrangler\index.js:9:51)
    at Object.<anonymous> (C:\Users\Kuldeep Raj Tiwari\Desktop\Marbles Example\marbles\app.js:44:50)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by Thibault-tech** [comment]
I have the same problem !
