### ISSUE TITLE
Error: Cannot find module 'grpc'

### ISSUE THREAD

**Issue by yeonchoii** [IBM-Blockchain-Archive/marbles#287]
Hello im blockchain novice student...!
 
$ node install_chaincode.js
getAdminSignedCertPEM()
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'grpc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/park/marbles/node_modules/fabric-ca-client/lib/Remote.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
How can i solve this problem..?
please help :(
thank you for my text~!

**Comment by dshuffma-ibm** [comment]
you need to install the dependencies: https://github.com/IBM-Blockchain/marbles/blob/master/docs/host_marbles_locally.md


`npm install` should pass with no errors
