### ISSUE TITLE
if I can run it under fabric 1.4?

### ISSUE THREAD

**Issue by gaozhenGo** [IBM-Blockchain-Archive/marbles#288]
# I got the master branch of marbles,and when i run it under fabric1.4,here are some problems

1. in fabric1.4,/fabcar/hfc-key-store has been replaced as /fabcar/javascript/wallet, and I fixed this problem by modifying connection_profile_lacal.json.

2. but here is **new problem**,when I try to run ```node install_chaincode.js```,it shows
```
---------------------------------------
info: Lets install some chaincode - marbles v4
---------------------------------------
info: First we enroll
debug: loading pem from a path: /home/cyan1/go/src/github.com/hyperledger/fabric/fabric-samples/basic-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/cd96d5260ad4757551ed4a5a991e62130f8008a0bf996e4e4b84cd097a747fec_sk
debug: loading pem from a path: /home/cyan1/go/src/github.com/hyperledger/fabric/fabric-samples/basic-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/admincerts/Admin@org1.example.com-cert.pem
info: [fcw] Going to enroll with admin cert!  peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1, orderer_url=grpc://localhost:7050, msp_id=Org1MSP
debug: added peer grpc://localhost:7051
debug: [fcw] Successfully got enrollment marblesDockerComposeNetworkmychannelOrg1MSPfabricpeerorg1
---------------------------------------
info: Now we install
---------------------------------------
debug: [fcw] Installing Chaincode
debug: [fcw] Sending install req targets=[grpc.http2.keepalive_time=300, grpc.keepalive_time_ms=300000, grpc.http2.keepalive_timeout=35, grpc.keepalive_timeout_ms=3500, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-node/1.10.1, _url=grpc://localhost:7051, addr=localhost:7051, , _request_timeout=90000, , _name=null], chaincodePath=marbles, chaincodeId=marbles, chaincodeVersion=v4
info: [packager/Golang.js]: packaging GOLANG from marbles
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: EOF
    at new createStatusError (/home/cyan1/go/src/github.com/marbles-master/node_modules/grpc/src/client.js:64:15)
    at /home/cyan1/go/src/github.com/marbles-master/node_modules/grpc/src/client.js:583:15
error: [fcw] Failed to obtain endorsement for transaction. code=14, , details=EOF
error: [fcw] Error in install catch block object code=14, , details=EOF
---------------------------------------
info: Install done. Errors: parsed=Blockchain network error - EOF, raw=[code=14, , details=EOF]
```

and how can I fix it?

**Comment by aonoa** [comment]
I have the same problem as you，How did you solve it？

**Comment by dshuffma-ibm** [comment]
sorry @aonoa but this marbles repo is unsupported these days. it was archived and moved to the **IBM-Blockchain-Archive** org.  unless this project gets rejuvenated, I wouldn't expect any help.  you may want to check out the other Fabric example in [fabric-samples](https://github.com/hyperledger/fabric-samples). `fabcar` is pretty popular.

**Comment by aonoa** [comment]
> sorry @aonoa but this marbles repo is unsupported these days. it was archived and moved to the **IBM-Blockchain-Archive** org. unless this project gets rejuvenated, I wouldn't expect any help. you may want to check out the other Fabric example in [fabric-samples](https://github.com/hyperledger/fabric-samples). `fabcar` is pretty popular.

Thank you for your reminder，I saw that some people have successfully configured it, I have tried many versions, but also encountered more problems, I can not solve them, can you tell me a method that can be successfully configured, such as marbles, fabric-samples , Node version combination, I think it may be caused by this reason failed.

**Comment by aonoa** [comment]
> 对不起，@ aonoa，但是最近这些弹珠储存库已不受支持。它已存档并移至**IBM-Blockchain-Archive**组织。除非这个项目恢复活力，否则我不会期望任何帮助。您可能想查看[fabric-samples中](https://github.com/hyperledger/fabric-samples)的另一个Fabric示例。`fabcar`非常受欢迎。

Thank you for your advice. I was forced to use the older version and successfully run marbles,
