### ISSUE TITLE
watch-sass error after building marbles app offline 

### ISSUE THREAD

**Issue by MrBuggySan** [IBM-Blockchain-Archive/marbles#36]
I'm trying to build the marbles app offline and connect it to a Bluemix blockchain.

after changing mycreds.json to appropriate values, installing dependencies I get this error:

```
[15:01:41] Using gulpfile ~/SchoolCode/capstone/marbles/gulpfile.js
[15:01:41] Starting 'build-sass'...
[15:01:41] Finished 'build-sass' after 16 ms
[15:01:41] Starting 'watch-sass'...
[15:01:41] 'watch-sass' errored after 9.2 ms
[15:01:41] Error: watch /home/andreibuiza/SchoolCode/capstone/marbles/scss/ ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:289:30)
    at /home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (/home/andreibuiza/SchoolCode/capstone/marbles/gulpfile.js:42:7)
    at module.exports (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/orchestrator/index.js:273:3)

```

Anyone have a clue to solve this ?

**Comment by dshuffma-ibm** [comment]
Its either your `gulp-sass` did not install correctly in your environment or the script isn't able to write to your file system.  Do you have any errors when running `npm install`? if that works fine then the script isn't able to write to its local disk.  disk could be full, or maybe permission of the script? though i think permissions would be a different error.

---

alternatively you could bypass sass completely.  Its only needed if you plan to edit the css/layout of the marbles application.  If you do not plan to modify it then simply comment it out from `gulpfile.js` by:

removing these line:

``` js
gulp.task('watch-sass', ['build-sass'], function () {
    gulp.watch(path.join(__dirname, '/scss/*.scss'), ['build-sass']);
});
```

and edit

``` js
gulp.task('default', ['watch-sass', 'watch-js', 'watch-server']);
```

to be

``` js
gulp.task('default', ['watch-js', 'watch-server']);
```

**Comment by MrBuggySan** [comment]
@dshuffma-ibm 

commeting out  watch-sass led to an error involving watch-js 

```
[16:26:20] Using gulpfile ~/SchoolCode/capstone/marbles/gulpfile.js
[16:26:20] Starting 'build-js-hash'...
[16:26:20] Finished 'build-js-hash' after 11 ms
[16:26:20] Starting 'watch-js'...
[16:26:20] 'watch-js' errored after 8.42 ms
[16:26:20] Error: watch /home/andreibuiza/SchoolCode/capstone/marbles/public/js/ ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:289:30)
    at /home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (/home/andreibuiza/SchoolCode/capstone/marbles/gulpfile.js:46:7)
    at module.exports (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/orchestrator/index.js:273:3)

```

I commented out watch-js as well and this time there is error but this time the server is able to run 

```
[16:27:50] Using gulpfile ~/SchoolCode/capstone/marbles/gulpfile.js
[16:27:50] Starting 'server'...
[16:27:50] Finished 'server' after 2.48 ms
[16:27:50] Starting 'watch-server'...
[16:27:50] 'watch-server' errored after 9.26 ms
[16:27:50] Error: watch /home/andreibuiza/SchoolCode/capstone/marbles/routes/ ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:289:30)
    at /home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (/home/andreibuiza/SchoolCode/capstone/marbles/gulpfile.js:50:7)
    at module.exports (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/andreibuiza/SchoolCode/capstone/marbles/node_modules/orchestrator/index.js:273:3)
cache busting hash js b6c91e67aae91b0a72d91073606ff4b4 css 5c5213ec16de93e801c4aaf7a7eb956b
------------------------------------------ Server Up - localhost:3000 ------------------------------------------
Running using Developer settings
- Tracking Deployment
loading hardcoded peers
loading hardcoded users
[ibc-js] Peer:  vp0-0150fa9c-167...:443
[ibc-js] Registering  vp0-0150fa9c-167...:443  w/enrollId - user_type1_709c4181a9
[ibc-js] Registration success x1 : user_type1_709c4181a9
[ibc-js] removing temp dir
[ibc-js] Downloading zip
redirect... https://codeload.github.com/IBM-Blockchain/marbles-chaincode/zip/master
[ibc-js] Downloading zip
[ibc-js] Unzipping zip
[ibc-js] Unzip done
[ibc-js] Scanning files [ 'part2_chaincode.go' ]
[ibc-js] Parsing file for shim version
[ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
[ibc-js] Parsing file for invoke functions - part2_chaincode.go
[ibc-js] Found cc invoke function:  init
[ibc-js] Found cc invoke function:  delete
[ibc-js] Found cc invoke function:  write
[ibc-js] Found cc invoke function:  init_marble
[ibc-js] Found cc invoke function:  set_user
[ibc-js] Found cc invoke function:  open_trade
[ibc-js] Found cc invoke function:  perform_trade
[ibc-js] Found cc invoke function:  remove_trade
[ibc-js] Parsing file for query functions - part2_chaincode.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
[ibc-js] Deploy Chaincode - Starting
[ibc-js]    function: init , arg: [ '99' ]


     Waiting...

```

The app is now working in the browser. Now I'm thinking if there's functionality/features that I will be missing if I go about with

`gulp.task('default', ['watch-server']);`

I can create and transfer marbles but maybe there is something else I'm missing I can't see?

**Comment by masterDev1985** [comment]
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

@MrBuggySan It could be that the watch command is trying to watch too many files at once.  I googled that `ENOSPC` error message from your logs and found the above SO thread.

**Comment by dshuffma-ibm** [comment]
also see this about `ENOSPC`: http://stackoverflow.com/questions/22475849/node-js-error-enospc

**Comment by MrBuggySan** [comment]
@masterDev1985 thank you for your suggestion

this solved it for me:

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

@dshuffma-ibm thank you for the support! 

Now, I have other problems and will be making another issue about it.
