### ISSUE TITLE
Unrecoverable error if peer[0] is unavailable

### ISSUE THREAD

**Issue by gemtot** [IBM-Blockchain-Archive/marbles#80]
Expected behaviour would be to gracefully roll over to another peer, but app throws an unhandled error event.

```
debug: [fcw] Querying Channel Stats:
info: [Chain.js]:  Primary peer was not set, using %s grpc.primary_user_agent=grpc-node/1.2.0, _url=grpcs://peer-us-east-2a.example.com:7051, addr=peer-us-east-2a.example.com:7051, , , _name=null, _roles=[]
info: Fetching block height...
debug: [fcw] Querying Channel Stats:
info: [Chain.js]:  Primary peer was not set, using %s grpc.primary_user_agent=grpc-node/1.2.0, _url=grpcs://peer-us-east-2a.example.com:7051, addr=peer-us-east-2a.example.com:7051, , , _name=null, _roles=[]
events.js:160
>>>>> Peer manually terminated here <<<<<
      throw er; // Unhandled 'error' event
      ^

Error: Endpoint read failed
    at ClientDuplexStream._emitStatusIfDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._readsDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:169:8)
    at readCallback (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:242:12)
```

Also if orderer[0] becomes unavailable, the app does not crash, but it does not attempt to connect to orderer[1].

```
debug: [fcw] Successfully obtained transaction endorsement
error: [Orderer.js]: sendBroadcast - on error: "Error: Connect Failed\n    at ClientDuplexStream._emitStatusIfDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:201:19)\n    at ClientDuplexStream._readsDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:169:8)\n    at readCallback (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:229:12)"
error: [fcw] Error in invoke catch block object Error: SERVICE_UNAVAILABLE
    at ClientDuplexStream.<anonymous> (/var/hyperledger/marbles/node_modules/fabric-client/lib/Orderer.js:117:21)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at ClientDuplexStream._emitStatusIfDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:204:12)
    at ClientDuplexStream._readsDone (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:169:8)
    at readCallback (/var/hyperledger/marbles/node_modules/grpc/src/node/src/client.js:229:12)
error: [fcw] could not format error
```

**Comment by dshuffma-ibm** [comment]
Yes, this is a known limitation.  I should be able to enhance this in the coming <strike>weeks</strike> eventually.

**Comment by dshuffma-ibm** [comment]
last week I've finally added changes that will retry on multiple peers for querys/invokes.  This also works for CAs during enrollment.  There is a [high_availability.js](https://github.com/IBM-Blockchain/marbles/blob/v4.0/utils/fc_wrangler/high_availability.js) file that performs the actual switching of peers/CAs.  

An example of it in use is during [invoke](https://github.com/IBM-Blockchain/marbles/blob/v4.0/utils/fc_wrangler/index.js#L56)
